In [9]:
import pandas as pd

df = pd.read_csv("spacex_sql_data.csv")

df.head()

,FlightNumber,Date,BoosterVersion,PayloadMass,Orbit,LaunchSite,Outcome,Flights,GridFins,Reused,Legs,LandingPad,Block,ReusedCount,Serial,Longitude,Latitude,Class,Year
0,1,2010,Falcon 9,6104.959412,LEO,CCAFS SLC 40,None None,1,False,False,False,NaN,1.0,0,B0003,-80.577366,28.561857,0,2010
1,2,2012,Falcon 9,525.000000,LEO,CCAFS SLC 40,None None,1,False,False,False,NaN,1.0,0,B0005,-80.577366,28.561857,0,2012
2,3,2013,Falcon 9,677.000000,ISS,CCAFS SLC 40,None None,1,False,False,False,NaN,1.0,0,B0007,-80.577366,28.561857,0,2013
3,4,2013,Falcon 9,500.000000,PO,VAFB SLC 4E,False Ocean,1,False,False,False,NaN,1.0,0,B1003,-120.610829,34.632093,0,2013
4,5,2013,Falcon 9,3170.000000,GTO,CCAFS SLC 40,None None,1,False,False,False,NaN,1.0,0,B1004,-80.577366,28.561857,0,2013

In [10]:
df.to_sql("SPACEXTBL", connection, if_exists="replace", index=False)

90

In [11]:
columns = pd.read_sql_query(
    "PRAGMA table_info(SPACEXTBL);",
    connection
)

columns[["name"]]

              name
0     FlightNumber
1             Date
2   BoosterVersion
3      PayloadMass
4            Orbit
5       LaunchSite
6          Outcome
7          Flights
8         GridFins
9           Reused
10            Legs
11      LandingPad
12           Block
13     ReusedCount
14          Serial
15       Longitude
16        Latitude
17           Class
18            Year

In [12]:
query = """
SELECT LaunchSite, COUNT(*) AS Number_of_Launches
FROM SPACEXTBL
GROUP BY LaunchSite
ORDER BY Number_of_Launches DESC;
"""

launch_site_analysis = pd.read_sql_query(query, connection)

launch_site_analysis

     LaunchSite  Number_of_Launches
0  CCAFS SLC 40                  55
1    KSC LC 39A                  22
2   VAFB SLC 4E                  13

In [13]:
query = """
SELECT LaunchSite,
       SUM(PayloadMass) AS Total_Payload_Mass
FROM SPACEXTBL
GROUP BY LaunchSite
ORDER BY Total_Payload_Mass DESC;
"""

payload_analysis = pd.read_sql_query(query, connection)

payload_analysis

     LaunchSite  Total_Payload_Mass
0  CCAFS SLC 40       305151.428235
1    KSC LC 39A       167341.918824
2   VAFB SLC 4E        76953.000000

In [14]:
query = """
SELECT LaunchSite,
       COUNT(*) AS Total_Launches,
       SUM(Class) AS Successful_Launches,
       ROUND(100.0 * SUM(Class) / COUNT(*), 2) AS Success_Rate
FROM SPACEXTBL
GROUP BY LaunchSite
ORDER BY Success_Rate DESC;
"""

success_rate_analysis = pd.read_sql_query(query, connection)

success_rate_analysis

     LaunchSite  Total_Launches  Successful_Launches  Success_Rate
0    KSC LC 39A              22                   17         77.27
1   VAFB SLC 4E              13                   10         76.92
2  CCAFS SLC 40              55                   33         60.00